apiVersion: v1
kind: Service
metadata:
  name: conduit-ui
spec:
  ports:
    - port: ${#toInt(parameters.loadbalancerPort)}
      protocol: TCP
      targetPort: ${#toInt(parameters.containerPort)}
  selector:
    app: conduit-ui
  type: LoadBalancer
